<?xml version="1.0" encoding="utf-8"?><Database Name="PuntryDB" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-A4B68L9\SQLEXPRESS;Initial Catalog=PuntryDB;Integrated Security=True" SettingsObjectName="PuntryProgram.Properties.Settings" SettingsPropertyName="PuntryDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.AccessLevels" Member="AccessLevels">
    <Type Name="AccessLevels">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="AccessLevels_Users" Member="Users" ThisKey="id" OtherKey="level_id" Type="Users" />
    </Type>
  </Table>
  <Table Name="dbo.FavoriteFiles" Member="FavoriteFiles">
    <Type Name="FavoriteFiles">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="file_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="user_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Files_FavoriteFiles" Member="Files" ThisKey="file_id" OtherKey="id" Type="Files" IsForeignKey="true" />
      <Association Name="Users_FavoriteFiles" Member="Users" ThisKey="user_id" OtherKey="id" Type="Users" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.FileChanges" Member="FileChanges">
    <Type Name="FileChanges">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="comment" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="datetime_up" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="file_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="user_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Files_FileChanges" Member="Files" ThisKey="file_id" OtherKey="id" Type="Files" IsForeignKey="true" />
      <Association Name="Users_FileChanges" Member="Users" ThisKey="user_id" OtherKey="id" Type="Users" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Files" Member="Files">
    <Type Name="Files">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="comment" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="data" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="extension" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="size" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="archive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="status_file_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="user_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Files_FavoriteFiles" Member="FavoriteFiles" ThisKey="id" OtherKey="file_id" Type="FavoriteFiles" />
      <Association Name="Files_FileChanges" Member="FileChanges" ThisKey="id" OtherKey="file_id" Type="FileChanges" />
      <Association Name="StatusFile_Files" Member="StatusFile" ThisKey="status_file_id" OtherKey="id" Type="StatusFile" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.StatusFile" Member="StatusFile">
    <Type Name="StatusFile">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="StatusFile_Files" Member="Files" ThisKey="id" OtherKey="status_file_id" Type="Files" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="Users">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="surname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="login" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="password" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="image" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="datetime_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="level_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="root" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Users_FavoriteFiles" Member="FavoriteFiles" ThisKey="id" OtherKey="user_id" Type="FavoriteFiles" />
      <Association Name="Users_FileChanges" Member="FileChanges" ThisKey="id" OtherKey="user_id" Type="FileChanges" />
      <Association Name="AccessLevels_Users" Member="AccessLevels" ThisKey="level_id" OtherKey="id" Type="AccessLevels" IsForeignKey="true" />
    </Type>
  </Table>
</Database>